# Generated by Django 4.0.5 on 2023-03-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train_dest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField(default=0, max_length=5)),
                ('train_name', models.CharField(default='', max_length=50)),
                ('station_code', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
