# Generated by Django 4.0.5 on 2023-03-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_tt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_dest',
            old_name='station_code',
            new_name='station_codes',
        ),
    ]
