# Generated by Django 4.0.5 on 2023-03-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_tt', '0002_rename_station_code_train_dest_station_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_dest',
            name='station_codes',
            field=models.TextField(default='', max_length=10),
        ),
    ]
