# Generated by Django 4.0.5 on 2023-03-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_tt', '0004_alter_train_dest_station_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_dest',
            name='reversed',
            field=models.BooleanField(default=False),
        ),
    ]
