# Generated by Django 4.0.5 on 2023-03-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_tt', '0005_train_dest_reversed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_dest',
            name='train_no',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
