# Generated by Django 4.0.5 on 2023-03-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_tt', '0006_alter_train_dest_train_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.CharField(default='0', max_length=5)),
                ('train_name', models.CharField(default='', max_length=50)),
                ('Coach', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
