# Generated by Django 4.0.5 on 2023-03-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_tt', '0007_coach_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coach_details',
            new_name='Coach_detail',
        ),
    ]
